# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DNWNowtiYfsr7FrJwvCaJWWV324O3Wne
"""

assignment 2
what you learn in today class
ans:
BASIC PYTHON SYNTAX
1. Back slach
2. triple quotes
3.string inside the quotes
4. escape sequence of string
4.formatted output
PYTHON VARIABLE
linking a data to the name
'if' 'def' 'and' dont used as variable
variable contains [upper case, lower case, number, underscore]
variable dont start6 with no.
TYPES OF OPERATOR
1. Arithmetic operator
2. comparison operator
3. assignment operator
4. bitwise operator
5. logical operator
6. membership operator
7. identity operator